repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    args:
    - --allow-multiple-documents
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: sort-simple-yaml
  - id: trailing-whitespace
  - id: no-commit-to-branch
    args:
    - --branch
    - main
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.1
  hooks:
  - id: go-fmt
  - id: go-vet
  - id: go-imports
  - id: golangci-lint
  - id: go-unit-tests
  - id: go-build
- repo: https://github.com/tekwizely/pre-commit-golang
  rev: v1.0.0-rc.1
  hooks:
  - id: go-mod-tidy
- repo: https://github.com/qoomon/git-conventional-commits
  rev: v2.7.2
  hooks:
  - id: conventional-commits
- repo: https://github.com/zricethezav/gitleaks
  rev: v8.24.0
  hooks:
  - id: gitleaks
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.44.0
  hooks:
  - id: markdownlint
    args:
    - --disable
    - MD013
  - id: markdownlint-fix
    args:
    - --disable
    - MD013
- repo: https://github.com/klieret/jekyll-relative-url-check
  rev: v2.0.2
  hooks:
  - id: jekyll-relative-url-check-markdown
- repo: https://github.com/golangci/golangci-lint
  rev: v1.64.8
  hooks:
  - id: golangci-lint
    args:
    - --fix
- repo: https://github.com/TekWizely/pre-commit-golang
  rev: v1.0.0-rc.1
  hooks:
  - id: go-mod-tidy-repo
  - id: go-build-repo-mod
  - id: go-test-repo-mod
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-golang
    args:
    - --autofix
  - id: pretty-format-yaml
    args:
    - --autofix
- repo: https://github.com/adrienverge/yamllint
  rev: v1.36.2
  hooks:
  - id: yamllint
    args:
    - --format
    - parsable
    - --strict
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.31.3
  hooks:
  - id: check-github-actions
  - id: check-github-workflows
